---
abstract: 'Perl Authentication and Authorization via cookies'
author:
  - 'Michael Schout <mschout@cpan.org>'
build_requires: {}
configure_requires:
  Apache::Test: '1.39'
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'Dist::Zilla version 6.006, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Apache-AuthCookie
requires:
  CGI: '3.12'
  Class::Load: '0.03'
  Test::More: '0.94'
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Apache-AuthCookie
  homepage: http://search.cpan.org/dist/Apache-AuthCookie/
  repository: git://github.com/mschout/apache-authcookie.git
version: '3.25'
x_serialization_backend: 'YAML::Tiny version 1.63'
